import React, { useState } from "react";
import { Copy, Check, Printer, RotateCcw } from "lucide-react";

// ── Markdown renderer ─────────────────────────────────────────────────────────
export function RenderText({ text }: { text: string }) {
  const lines = text.split("\n");
  return (
    <div style={{ lineHeight: 1.75, fontSize: ".88rem", color: "var(--text-primary)" }}>
      {lines.map((line, i) => {
        if (!line.trim()) return <br key={i} />;
        if (/^## /.test(line)) return (
          <p key={i} style={{ margin: ".9rem 0 .3rem", fontWeight: 700, fontSize: ".97rem", color: "var(--text-primary)", borderBottom: "1px solid var(--border-default)", paddingBottom: ".25rem" }}>
            {renderInline(line.replace(/^## /, ""))}
          </p>
        );
        if (/^### /.test(line)) return (
          <p key={i} style={{ margin: ".75rem 0 .2rem", fontWeight: 700, fontSize: ".91rem", color: "var(--text-primary)" }}>
            {renderInline(line.replace(/^### /, ""))}
          </p>
        );
        if (/^# /.test(line)) return (
          <p key={i} style={{ margin: ".9rem 0 .35rem", fontWeight: 800, fontSize: "1rem", color: "var(--text-primary)" }}>
            {renderInline(line.replace(/^# /, ""))}
          </p>
        );
        if (/^[-•*]\s/.test(line)) return (
          <div key={i} style={{ display: "flex", gap: ".5rem", margin: ".25rem 0" }}>
            <span style={{ color: "var(--clr-primary,#6366f1)", flexShrink: 0, marginTop: ".05rem" }}>•</span>
            <span>{renderInline(line.replace(/^[-•*]\s/, ""))}</span>
          </div>
        );
        if (/^\d+\.\s/.test(line)) {
          const num = line.match(/^\d+/)![0];
          return (
            <div key={i} style={{ display: "flex", gap: ".5rem", margin: ".25rem 0" }}>
              <span style={{ color: "var(--clr-primary,#6366f1)", flexShrink: 0, minWidth: "1.4rem", fontWeight: 600 }}>{num}.</span>
              <span>{renderInline(line.replace(/^\d+\.\s/, ""))}</span>
            </div>
          );
        }
        if (/^\*\*.*\*\*$/.test(line.trim())) return (
          <p key={i} style={{ margin: ".25rem 0", fontWeight: 600 }}>{renderInline(line)}</p>
        );
        return <p key={i} style={{ margin: ".2rem 0" }}>{renderInline(line)}</p>;
      })}
    </div>
  );
}

function renderInline(text: string): React.ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g);
  return parts.map((p, i) => {
    if (p.startsWith("**") && p.endsWith("**")) return <strong key={i} style={{ fontWeight: 700, color: "var(--text-primary)" }}>{p.slice(2, -2)}</strong>;
    if (p.startsWith("`") && p.endsWith("`")) return <code key={i} style={{ background: "var(--bg-subtle)", padding: ".1em .35em", borderRadius: 4, fontSize: ".83em", fontFamily: "monospace", color: "var(--text-primary)" }}>{p.slice(1, -1)}</code>;
    return <span key={i}>{p}</span>;
  });
}

// ── Report card with copy + print ─────────────────────────────────────────────
export function ReportCard({
  title, subtitle, report, onRegenerate, loading, accentColor = "#6366f1",
}: {
  title: string; subtitle?: string; report: string;
  onRegenerate?: () => void; loading?: boolean; accentColor?: string;
}) {
  const [copied, setCopied] = useState(false);

  const copy = async () => {
    await navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const print = () => {
    const w = window.open("", "_blank");
    if (!w) return;
    const html = report
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/^## (.+)$/gm, "<h2>$1</h2>")
      .replace(/^### (.+)$/gm, "<h3>$1</h3>")
      .replace(/^# (.+)$/gm, "<h1>$1</h1>")
      .replace(/^[-•*] (.+)$/gm, "<li>$1</li>")
      .replace(/^\d+\. (.+)$/gm, "<li>$1</li>")
      .replace(/\n/g, "<br>");
    w.document.write(`<!DOCTYPE html><html><head><title>${title}</title><style>
      body{font-family:Arial,sans-serif;max-width:720px;margin:2rem auto;line-height:1.7;color:#111;font-size:14px}
      h1{font-size:1.25rem;margin:1rem 0 .3rem}h2{font-size:1.05rem;border-bottom:1px solid #ddd;padding-bottom:.2rem;margin:.9rem 0 .3rem}
      h3{font-size:.95rem;margin:.75rem 0 .2rem}p,br{margin:.2rem 0}li{margin:.2rem 0 .2rem 1.2rem}
      strong{font-weight:600}
    </style></head><body>
      <h1>${title}</h1>
      ${subtitle ? `<p style="color:#666;margin-bottom:1.5rem">${subtitle}</p>` : ""}
      ${html}
      <p style="margin-top:2rem;font-size:.78rem;color:#999">Generated by Plasticon AI — ${new Date().toLocaleString()}</p>
    </body></html>`);
    w.document.close(); w.print();
  };

  return (
    <div style={{ background: "var(--bg-surface)", border: "1px solid var(--border-default)", borderRadius: 14, overflow: "hidden", boxShadow: "0 2px 8px rgba(0,0,0,.06)" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: ".9rem 1.15rem", borderBottom: "1px solid var(--border-default)", background: `linear-gradient(135deg, ${accentColor}10, ${accentColor}04)` }}>
        <div style={{ display: "flex", alignItems: "center", gap: ".65rem" }}>
          <div style={{ width: 3, height: 30, borderRadius: 999, background: `linear-gradient(to bottom, ${accentColor}, ${accentColor}55)`, flexShrink: 0 }} />
          <div>
            <p style={{ margin: 0, fontSize: ".88rem", fontWeight: 700, color: "var(--text-primary)" }}>{title}</p>
            {subtitle && <p style={{ margin: ".1rem 0 0", fontSize: ".72rem", color: "var(--text-muted)" }}>{subtitle}</p>}
          </div>
        </div>
        <div style={{ display: "flex", gap: ".35rem" }}>
          {onRegenerate && (
            <IconBtn onClick={onRegenerate} disabled={loading} title="Regenerate">
              <RotateCcw size={13} style={loading ? { animation: "spin 1s linear infinite" } : {}} />
            </IconBtn>
          )}
          <IconBtn onClick={print} title="Print / Save PDF"><Printer size={13} /></IconBtn>
          <IconBtn onClick={() => void copy()} title="Copy text" active={copied}>
            {copied ? <Check size={13} /> : <Copy size={13} />}
          </IconBtn>
        </div>
      </div>
      <div style={{ padding: "1.3rem 1.4rem", overflowY: "auto", maxHeight: "calc(100vh - 280px)" }}>
        <RenderText text={report} />
      </div>
    </div>
  );
}

function IconBtn({ children, onClick, disabled, title, active }: {
  children: React.ReactNode; onClick: () => void; disabled?: boolean; title?: string; active?: boolean;
}) {
  return (
    <button
      type="button" onClick={onClick} disabled={disabled} title={title}
      style={{ width: 30, height: 30, border: "1px solid var(--border-default)", borderRadius: 7, background: active ? "#dcfce7" : "transparent", cursor: disabled ? "default" : "pointer", display: "flex", alignItems: "center", justifyContent: "center", color: active ? "#16a34a" : "var(--text-secondary)", transition: "all .15s" }}
    >
      {children}
    </button>
  );
}

// ── Page header ───────────────────────────────────────────────────────────────
export function AIPageHeader({ icon: Icon, gradient, title, subtitle, badge }: {
  icon: React.ComponentType<{ size?: number; color?: string }>;
  gradient: [string, string]; title: string; subtitle: string; badge?: string;
}) {
  const [from, to] = gradient;
  return (
    <div style={{ display: "flex", alignItems: "center", gap: "1rem", marginBottom: "1.75rem", padding: "1.1rem 1.35rem", background: `linear-gradient(135deg, ${from}12, ${to}06)`, border: `1px solid ${from}28`, borderRadius: 14, boxShadow: `0 2px 12px ${from}14` }}>
      <div style={{ width: 48, height: 48, borderRadius: 13, background: `linear-gradient(135deg, ${from}, ${to})`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, boxShadow: `0 4px 14px ${from}45` }}>
        <Icon size={23} color="#fff" />
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: "flex", alignItems: "center", gap: ".6rem", flexWrap: "wrap" }}>
          <h1 style={{ margin: 0, fontSize: "1.1rem", fontWeight: 800, color: "var(--text-primary)" }}>{title}</h1>
          {badge && (
            <span style={{ padding: ".2rem .6rem", borderRadius: 999, fontSize: ".67rem", fontWeight: 700, background: `${from}20`, color: from, letterSpacing: ".05em", textTransform: "uppercase" as const }}>
              {badge}
            </span>
          )}
        </div>
        <p style={{ margin: ".25rem 0 0", fontSize: ".8rem", color: "var(--text-muted)", whiteSpace: "pre-wrap" }}>{subtitle}</p>
      </div>
    </div>
  );
}

// ── Stat card ─────────────────────────────────────────────────────────────────
export function StatCard({ label, value, color, icon: Icon, subtext }: {
  label: string; value: string | number; color: string;
  icon?: React.ComponentType<{ size?: number; color?: string }>; subtext?: string;
}) {
  return (
    <div style={{ flex: 1, minWidth: 130, padding: "1rem 1.1rem", background: "var(--bg-surface)", border: "1px solid var(--border-default)", borderRadius: 12, borderTop: `3px solid ${color}`, boxShadow: "0 1px 4px rgba(0,0,0,.05)" }}>
      {Icon && <Icon size={15} color={color} />}
      <p style={{ margin: Icon ? ".35rem 0 0" : "0", fontSize: "1.5rem", fontWeight: 800, color, lineHeight: 1.1 }}>{value}</p>
      <p style={{ margin: ".3rem 0 0", fontSize: ".72rem", color: "var(--text-muted)", fontWeight: 500 }}>{label}</p>
      {subtext && <p style={{ margin: ".1rem 0 0", fontSize: ".69rem", color: "var(--text-muted)", opacity: .75 }}>{subtext}</p>}
    </div>
  );
}

// ── Form helpers ──────────────────────────────────────────────────────────────
export function FormField({ label, required, hint, children }: {
  label: string; required?: boolean; hint?: string; children: React.ReactNode;
}) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: ".3rem" }}>
      <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}>
        <label style={{ fontSize: ".78rem", fontWeight: 600, color: "var(--text-secondary)" }}>
          {label}{required && <span style={{ color: "#ef4444", marginLeft: ".2rem" }}>*</span>}
        </label>
        {hint && <span style={{ fontSize: ".7rem", color: "var(--text-muted)" }}>{hint}</span>}
      </div>
      {children}
    </div>
  );
}

export const inputCss: React.CSSProperties = {
  padding: ".6rem .9rem", border: "1px solid var(--border-default)", borderRadius: 9,
  background: "var(--bg-default)", color: "var(--text-primary)", fontSize: ".88rem",
  fontFamily: "inherit", outline: "none", width: "100%", boxSizing: "border-box" as const, transition: "border-color .15s",
};

// ── Action button ─────────────────────────────────────────────────────────────
export function AIButton({ gradient, onClick, disabled, loading, loadingText = "Processing…", icon: Icon, children }: {
  gradient: [string, string]; onClick: () => void; disabled?: boolean; loading?: boolean;
  loadingText?: string; icon?: React.ComponentType<{ size?: number }>; children: React.ReactNode;
}) {
  const [from, to] = gradient;
  const off = disabled || loading;
  return (
    <button type="button" onClick={onClick} disabled={off} style={{ padding: ".65rem 1.4rem", border: "none", borderRadius: 9, cursor: off ? "default" : "pointer", background: off ? "var(--bg-subtle)" : `linear-gradient(135deg, ${from}, ${to})`, color: off ? "var(--text-muted)" : "#fff", fontWeight: 700, fontSize: ".88rem", display: "flex", alignItems: "center", justifyContent: "center", gap: ".45rem", boxShadow: off ? "none" : `0 3px 10px ${from}40`, letterSpacing: ".01em", whiteSpace: "nowrap" as const, transition: "box-shadow .15s" }}>
      {loading ? <><RotateCcw size={15} style={{ animation: "spin 1s linear infinite" }} />{loadingText}</> : <>{Icon && <Icon size={15} />}{children}</>}
    </button>
  );
}

// ── Empty result state ─────────────────────────────────────────────────────────
export function AIEmptyState({ icon: Icon, title, description, color = "#6366f1" }: {
  icon: React.ComponentType<{ size?: number; color?: string }>;
  title: string; description?: string; color?: string;
}) {
  return (
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "3rem 2rem", textAlign: "center", background: "var(--bg-surface)", border: "1px solid var(--border-default)", borderRadius: 14, gap: ".75rem" }}>
      <div style={{ width: 56, height: 56, borderRadius: "50%", background: `${color}18`, display: "flex", alignItems: "center", justifyContent: "center" }}>
        <Icon size={26} color={color} />
      </div>
      <div>
        <p style={{ margin: 0, fontWeight: 700, color: "var(--text-primary)", fontSize: ".95rem" }}>{title}</p>
        {description && <p style={{ margin: ".4rem 0 0", fontSize: ".82rem", color: "var(--text-muted)", maxWidth: 340, lineHeight: 1.55 }}>{description}</p>}
      </div>
    </div>
  );
}

// ── Global keyframes (inject once) ────────────────────────────────────────────
export function AIKeyframes() {
  return (
    <style>{`
      @keyframes spin { to { transform: rotate(360deg); } }
      @keyframes ai-pulse { 0%,100% { opacity:.25; transform:scale(.85); } 50% { opacity:1; transform:scale(1.1); } }
      @keyframes ai-fadein { from { opacity:0; transform:translateY(6px); } to { opacity:1; transform:none; } }
    `}</style>
  );
}

// ── Severity badge ─────────────────────────────────────────────────────────────
export function SeverityBadge({ level }: { level: "HIGH" | "MEDIUM" | "LOW" }) {
  const map = {
    HIGH:   { bg: "#fee2e2", color: "#dc2626", label: "High" },
    MEDIUM: { bg: "#fef3c7", color: "#d97706", label: "Medium" },
    LOW:    { bg: "#dcfce7", color: "#16a34a", label: "Low" },
  };
  const { bg, color, label } = map[level];
  return (
    <span style={{ padding: ".2rem .55rem", borderRadius: 999, fontSize: ".7rem", fontWeight: 700, background: bg, color, letterSpacing: ".03em" }}>
      {label}
    </span>
  );
}
