import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../../api/client';
import { ScreenHeader } from '../../components';
import { colors, radius, shadow, spacing, typography } from '../../theme';

interface FinancialReport {
  id: number;
  title?: string;
  reportType?: string;
  period?: string;
  pdfPath?: string;
  generatedBy?: { fullName: string };
  createdAt: string;
}

const TYPE_COLOR: Record<string, string> = {
  'P&L':          colors.success,
  BalanceSheet:   colors.primary,
  CashFlow:       colors.info,
  TaxReport:      colors.warning,
  Payroll:        colors.accent,
};

function ReportCard({ item }: { item: FinancialReport }) {
  const color = TYPE_COLOR[item.reportType ?? ''] ?? colors.textMuted;
  return (
    <View style={styles.card}>
      <View style={styles.cardTop}>
        <View style={[styles.iconWrap, { backgroundColor: `${color}15` }]}>
          <Ionicons name="document-text" size={20} color={color} />
        </View>
        <View style={styles.cardContent}>
          <Text style={styles.title} numberOfLines={1}>{item.title ?? item.reportType ?? `Report #${item.id}`}</Text>
          <Text style={styles.period}>{item.period ?? new Date(item.createdAt).toLocaleDateString([], { month: 'long', year: 'numeric' })}</Text>
        </View>
        {item.reportType && (
          <View style={[styles.typeBadge, { backgroundColor: `${color}15` }]}>
            <Text style={[styles.typeText, { color }]}>{item.reportType}</Text>
          </View>
        )}
      </View>
      <View style={styles.footer}>
        <Ionicons name="time-outline" size={12} color={colors.textMuted} />
        <Text style={styles.meta}>
          {new Date(item.createdAt).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' })}
          {item.generatedBy ? ` · ${item.generatedBy.fullName}` : ''}
        </Text>
        {item.pdfPath && (
          <View style={styles.pdfBadge}>
            <Ionicons name="attach-outline" size={12} color={colors.primary} />
            <Text style={styles.pdfText}>PDF</Text>
          </View>
        )}
      </View>
    </View>
  );
}

export function FinancialReportsScreen() {
  const [reports, setReports]   = useState<FinancialReport[]>([]);
  const [loading, setLoading]   = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async () => {
    try {
      const res = await api.get<FinancialReport[]>('/financial-reports?limit=30');
      setReports(Array.isArray(res) ? res : []);
    } catch (e: any) {
      Alert.alert('Error', e?.message ?? 'Failed to load reports');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => { void load(); }, [load]);

  return (
    <SafeAreaView style={styles.safe}>
      <ScreenHeader title="Financial Reports" subtitle={`${reports.length} report${reports.length !== 1 ? 's' : ''}`} showBack />
      {loading ? <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View> : (
        <FlatList
          data={reports}
          keyExtractor={(i, idx) => `${String(i.id)}-${idx}`}
          renderItem={({ item }) => <ReportCard item={item} />}
          contentContainerStyle={styles.list}
          showsVerticalScrollIndicator={false}
          refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} tintColor={colors.primary} />}
          ListEmptyComponent={
            <View style={styles.empty}>
              <Ionicons name="document-outline" size={44} color={colors.textMuted} />
              <Text style={styles.emptyText}>No reports available</Text>
              <Text style={styles.emptyHint}>Reports are generated by finance managers on the web dashboard</Text>
            </View>
          }
        />
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe:        { flex: 1, backgroundColor: colors.background },
  center:      { flex: 1, alignItems: 'center', justifyContent: 'center' },
  list:        { padding: spacing.md, paddingBottom: 40 },
  card:        { backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.md, marginBottom: spacing.sm, ...shadow.sm },
  cardTop:     { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, marginBottom: spacing.sm },
  iconWrap:    { width: 40, height: 40, borderRadius: radius.sm, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  cardContent: { flex: 1 },
  title:       { ...typography.h4 },
  period:      { ...typography.caption, color: colors.textMuted, marginTop: 2 },
  typeBadge:   { paddingHorizontal: 8, paddingVertical: 3, borderRadius: radius.full, flexShrink: 0 },
  typeText:    { fontSize: 10, fontWeight: '700' },
  footer:      { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: spacing.sm },
  meta:        { ...typography.caption, color: colors.textMuted, flex: 1 },
  pdfBadge:    { flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 6, paddingVertical: 2, borderRadius: radius.sm, backgroundColor: `${colors.primary}15` },
  pdfText:     { fontSize: 10, fontWeight: '700', color: colors.primary },
  empty:       { alignItems: 'center', paddingTop: 60, gap: spacing.sm, paddingHorizontal: spacing.lg },
  emptyText:   { ...typography.bodySmall, color: colors.textMuted },
  emptyHint:   { ...typography.caption, color: colors.textMuted, textAlign: 'center' },
});
